# Generated by Django 3.1.2 on 2020-11-04 00:08

from django.db import migrations, models
import project_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20201104_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250, validators=[project_app.validators.ingredients_validator], verbose_name="Ingredients (Please separate the ingredients with ','"),
        ),
    ]
